Sprint1
ClevertecFrontendLab/sprint1-KaPuTaH-UluTka pull request #1
Opened 2023-02-01 14:37 UTC by KaPuTaH-UluTka

2023-02-01 14:40 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 6.
Количество непройденных тестов: 0.
***
**book-page 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1675262434/book-page%20320px.png)
***
**book-page 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1675262434/book-page%20768px.png)
***
**book-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1675262434/book-page.png)
***
**content-list 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1675262434/content-list%20320px.png)
***
**content-list 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1675262434/content-list%20768px.png)
***
**content-list.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1675262434/content-list.png)
***
**content-window 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1675262434/content-window%20320px.png)
***
**content-window 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1675262434/content-window%20768px.png)
***
**content-window.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1675262434/content-window.png)

2023-02-01 14:46 UTC, Gaurrus requested changes

2023-02-01 14:46 UTC, Gaurrus commented on src/assets/books.json
> +    "image": "https://i.ibb.co/9NXDjMy/book.png",
так не пойдет, нужно экспортировать все картинки и положить в assets рядом с компонетом, иначе автотесты не успевают подгружать их и скриншоты кривые - нужно переделать

2023-02-01 15:13 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 6.
Количество непройденных тестов: 0.
***
**book-page 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1675264399/book-page%20320px.png)
***
**book-page 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1675264399/book-page%20768px.png)
***
**book-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1675264399/book-page.png)
***
**content-list 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1675264399/content-list%20320px.png)
***
**content-list 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1675264399/content-list%20768px.png)
***
**content-list.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1675264399/content-list.png)
***
**content-window 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1675264399/content-window%20320px.png)
***
**content-window 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1675264399/content-window%20768px.png)
***
**content-window.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1675264399/content-window.png)

2023-02-01 16:35 UTC, Gaurrus requested changes

2023-02-01 16:35 UTC, Gaurrus commented on src/components/book-rating/book-rating.tsx
> +        alt={props.rating === 5 ? 'filled-star' : 'star'}/></div>);
промапать надо

2023-02-01 16:35 UTC, Gaurrus commented on src/pages/main/book-list/book-card/book-card-list.module.scss
> +        font-weight: 400;
чтобы не задавать каждому элементу стили можно описать их родительскому элементу, например body, а дочерние наследуют, если всё правильно сделано) - сэкономит много строк кода

2023-02-01 16:35 UTC, Gaurrus commented on src/pages/main/book-list/book-card/book-card.tsx
> +        if(window.innerWidth < 400 && props.book.name.length > 30) return `${props.book.name.slice(0, 30)}...`
это проще решить средствами css - text-overflow

2023-02-01 16:35 UTC, Gaurrus commented on src/pages/main/book-list/list-settings/list-settings.tsx
> +                <button className={classes['change-view-btn']} style={props.listState ? {'background':gradient}:{}} onClick={()=>props.setListState(true)} type="button"
все инлайновые стили убрать, реализовать через css

2023-02-01 16:35 UTC, Gaurrus commented on src/pages/main/main-page.tsx
> +    </section>
надо сделать через нормальный роутинг

2023-02-01 16:35 UTC, Gaurrus commented on src/pages/main/view/view.tsx
> +    console.log(123)
консоль кому осталась?) убираем все консольки

2023-02-01 22:18 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 6.
Количество непройденных тестов: 0.
***
**book-page 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1675289896/book-page%20320px.png)
***
**book-page 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1675289896/book-page%20768px.png)
***
**book-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1675289896/book-page.png)
***
**content-list 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1675289896/content-list%20320px.png)
***
**content-list 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1675289896/content-list%20768px.png)
***
**content-list.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1675289896/content-list.png)
***
**content-window 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1675289896/content-window%20320px.png)
***
**content-window 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1675289896/content-window%20768px.png)
***
**content-window.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1675289896/content-window.png)

2023-02-01 22:29 UTC, KaPuTaH-UluTka commented on src/components/book-rating/book-rating.tsx
> +        alt={props.rating === 5 ? 'filled-star' : 'star'}/></div>);
Доброй ночи, остальное пофиксил, а вот тут вопрос. Возможно я туповат=) Сделал с мапами, но пришлось тогда выключить правило в линтере на индекс массива в ключе, ибо я не совсем понимаю, как решить это по-другому и короче. Буду благодарен за подсказку и надеюсь больше критичных моментов нет, чтобы успеть к дедлайну=)

2023-02-01 22:30 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 6.
Количество непройденных тестов: 0.
***
**book-page 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1675290642/book-page%20320px.png)
***
**book-page 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1675290642/book-page%20768px.png)
***
**book-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1675290642/book-page.png)
***
**content-list 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1675290642/content-list%20320px.png)
***
**content-list 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1675290642/content-list%20768px.png)
***
**content-list.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1675290642/content-list.png)
***
**content-window 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1675290642/content-window%20320px.png)
***
**content-window 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1675290642/content-window%20768px.png)
***
**content-window.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1675290642/content-window.png)

2023-02-02 05:35 UTC, Gaurrus commented on src/components/book-rating/book-rating.tsx
> +        alt={props.rating === 5 ? 'filled-star' : 'star'}/></div>);
key просто прописываешь для элементов, обычно передается какой-нибудь id например в него или имя если имена у всех элементов массива разные

2023-02-02 05:35 UTC, Gaurrus approved these changes

2023-02-02 06:11 UTC, merged